# sample environment containing some libraries
channels:
- defaults
- conda-forge
- districtdatalabs
dependencies:
- python=3.6.7
- numpy=1.16.2
- scipy=1.1.0
- scikit-learn=0.20.2
- jupyter=1.0.0
- pandas=0.23.4
- nltk=3.3.0
- ipykernel=4.10.0
- scikit-plot
- scikit-optimize
- pathlib
- keras=2.2.2
- pip=18.0
- pip:
  - xgboost
  - bayesian-optimization
